name: Deploy to Railway

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install PHP
        run: |
          sudo apt-get install -y php-cli php-mbstring php-xml php-fpm

      - name: Build or prepare PHP project
        # Add your project-specific build or preparation commands here

      - name: Deploy to Railway
        uses: bervProject/railway-deploy@main
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          service: login-production-9b0a.up
