name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Railway
        uses: railwayapp/github-action@v2
        with:
          apiKey: ${{ secrets.RAILWAY_API_KEY }}
          projectId: ${{ secrets.RAILWAY_PROJECT_ID }}
